[build]
  publish = "dist"
  command = "npm run generate && npm run build:api"
  functions = "./functions"
[build.environment]
  NODE_VERSION = "10"
  YARN_VERSION = "1.13.0"
  YARN_FLAGS = "--no-ignore-optional"
[template.environment]
  SENDGRID_API_KEY = "Your Sendgrid API Key (required for newsletter signup box)"
  SENDGRID_WELCOME_SENDER_EMAIL = "Sendgrid Welcome Sender Email"
  SENDGRID_WELCOME_SENDER_NAME = "Sendgrid Welcome Sender Name"
  SENDGRID_WELCOME_TEMPLATE_ID = "Sendgrid Welcome Email Template ID"